#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_preonic_1x2uC(
		KC_GRV,     KC_1,       KC_2,       KC_3,       KC_4,   KC_5,   KC_6,   KC_7,   KC_8,       KC_9,       KC_0,       KC_BSPC, 
		KC_TAB,     KC_Q,       KC_W,       KC_E,       KC_R,   KC_T,   KC_Y,   KC_U,   KC_I,       KC_O,       KC_P,       KC_DEL, 
		KC_ESC,     KC_A,       KC_S,       KC_D,       KC_F,   KC_G,   KC_H,   KC_J,   KC_K,       KC_L,       KC_SCLN,    KC_LBRC, 
		KC_LSFT,    KC_Z,       KC_X,       KC_C,       KC_V,   KC_B,   KC_N,   KC_M,   KC_COMM,    KC_DOT,     KC_UP,      KC_ENT, 
		KC_LCTL,    KC_LGUI,    KC_LALT,    KC_NUBS,    MO(1),      KC_SPC,     MO(2),  KC_SLSH,    KC_LEFT,    KC_DOWN,    KC_RGHT
		),
	
    [1] = LAYOUT_preonic_1x2uC(
        KC_ESC,         KC_TRNS,    KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_TRNS,        KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_MINS,    KC_EQL,     LSFT(KC_MINS), 
        KC_TAB,         RALT(KC_Q), KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_TRNS,        KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_LBRC,    KC_RBRC,    KC_TRNS, 
        KC_APP,         KC_TRNS,    KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_TRNS,        KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_QUOT,    KC_NUHS,    KC_TRNS, 
        RALT(KC_MINS),  KC_NUBS,    LSFT(KC_NUBS),  KC_QUOT,    KC_NUHS,    LSFT(KC_QUOT),  LSFT(KC_NUHS),  KC_ASTR,    KC_LPRN,    KC_TRNS,    KC_WH_U,    KC_TRNS, 
        LCTL(KC_F1),    KC_TRNS,    KC_RALT,        KC_TRNS,    KC_TRNS,            LALT(KC_TAB),           MO(3),      KC_TRNS,    KC_TRNS,    KC_WH_D,    KC_TRNS
        ),
	
    [2] = LAYOUT_preonic_1x2uC(
        KC_F12,         KC_F1,      KC_F2,      KC_F3,      KC_F4,  KC_F5,  KC_F6,  KC_F7,      KC_F8,      KC_F9,      KC_F10,    KC_F11, 
        KC_NO,          KC_NO,      KC_NO,      KC_NO,      KC_NO,  KC_NO,  KC_NO,  KC_NO,      KC_INS,     KC_NO,      KC_PSCR,   KC_NO, 
        KC_NO,          KC_NO,      KC_NO,      KC_NO,      KC_NO,  KC_NO,  KC_NO,  KC_NO,      KC_NO,      KC_NO,      KC_NO,     KC_NO, 
        KC_NO,          KC_NO,      KC_NO,      KC_NO,      KC_NO,  KC_NO,  KC_NO,  KC_NO,      KC_NO,      KC_NO,      KC_PGUP,   KC_ENT, 
        LCA(KC_DEL),    KC_LGUI,    KC_RALT,    KC_CAPS,    MO(3),      KC_SPC,     KC_TRNS,    KC_NO,      KC_HOME,    KC_PGDN,   KC_END
        ),
	
    [3] = LAYOUT_preonic_1x2uC(
        KC_F1,      KC_F2,      KC_F3,      KC_F4,      KC_F5,   KC_F6,     KC_F7,      KC_F8,         KC_F9,          KC_F10,     KC_F11,     KC_F12, 
        KC_NO,      RESET,      DEBUG,      KC_NO,      KC_NO,   KC_NO,     KC_NO,      TERM_ON,       TERM_OFF,       KC_NO,      KC_NO,      KC_NO, 
        KC_NO,      KC_NO,      MU_MOD,     AU_ON,      AU_OFF,  KC_NO,     KC_NO,      DF(0),         KC_NO,          KC_NO,      KC_NO,      KC_NO, 
        KC_NO,      MUV_DE,     MUV_IN,     MU_ON,      MU_OFF,  MI_ON,     MI_OFF,     KC_NO,         KC_NO,          KC_NO,      KC_TRNS,    NK_TOGG, 
        KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,    KC_TRNS,      KC_TRNS,          KC_TRNS,       KC_TRNS,        KC_TRNS,    KC_TRNS,    KC_TRNS
        )
};


